# Generated by Django 5.0.2 on 2024-02-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_creation_date_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства продукта'),
        ),
    ]
